/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAdminP;
import ec.edu.ups.controlador.ControladorUsuarioP;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VntIniciarsesionI2 extends javax.swing.JInternalFrame {
    private ControladorAdminP ctrlAdmin;
    private ControladorUsuarioP ctrlUsuario;
    private VntPrincipalI2 vntPrincipal;
    private boolean sesionAdmin;
    /**
     * Creates new form VntIniciarsesion
     * @param ctrlUsuario
     * @param ctrlAdmin
     * @param vntPrincipal
     */
    public VntIniciarsesionI2(ControladorUsuarioP ctrlUsuario, ControladorAdminP ctrlAdmin, VntPrincipalI2 vntPrincipal) {
        initComponents();
        this.ctrlUsuario = ctrlUsuario;
        this.ctrlAdmin = ctrlAdmin;
        this.vntPrincipal = vntPrincipal;
    }

    public boolean isSesionAdmin() {
        return sesionAdmin;
    }

    public void setSesionAdmin(boolean sesionAdmin) {
        this.sesionAdmin = sesionAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Inciar Sesion");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imgs/loguin.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Correo");

        jLabel2.setText("Contraseña");

        btnIniciar.setText("INICIAR SESION");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnCancelar))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        String correo = txtCorreo.getText();
        String contrasenia = txtContrasenia.getText();
        
        System.out.println("---> " + ctrlAdmin.iniciarSesionA(correo, contrasenia));
        if (ctrlAdmin.iniciarSesionA(correo, contrasenia)) {
            JOptionPane.showMessageDialog(this, "Bienvenido Administrador" + "\nIniciado correctamente");
            System.out.println("adminInLissussss --> " + ctrlUsuario.getListaObjetos());
            vntPrincipal.getListarMenuItem().setVisible(true);
            vntPrincipal.getRegistarUMenuItem().setVisible(true);
            vntPrincipal.getGestionMenu().setVisible(true);
            JOptionPane.showMessageDialog(this, "Ya pueden registrarse los usuarios "
                    + "\n Puede cerrar sesion o verificar la lista de los autos registrados");
            
            sesionAdmin = true;
            this.dispose();
            
        }else if (ctrlUsuario.iniciarSesionU(correo, contrasenia)) {
            JOptionPane.showMessageDialog(this, "Bienvenido" + "\nIniciado correctamente");
            vntPrincipal.getListarMenuItem().setVisible(false);
            vntPrincipal.getGestionMenu().setVisible(true);
            vntPrincipal.getReservarMenuItem().setVisible(true);
            vntPrincipal.getRetirarMenuItem().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
            txtContrasenia.setText("");
            txtCorreo.setText("");
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        txtContrasenia.setText("");
        txtCorreo.setText("");
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
