/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAdminP;
import ec.edu.ups.controlador.ControladorUsuarioP;
import ec.edu.ups.modelo.AdminP;
import ec.edu.ups.vista.VntPrincipalI2;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VntRegistrarAdminI2 extends javax.swing.JInternalFrame {

    private ControladorAdminP ctrlAdmin;
    private ControladorUsuarioP ctrlUsuario;
    private VntPrincipalI2 vntPrincipal;

    /**
     * Creates new form VntRegistrar
     *
     * @param ctrlUsuario
     * @param ctrlAdmin
     * @param vntPrincipal
     */
    public VntRegistrarAdminI2(ControladorUsuarioP ctrlUsuario, ControladorAdminP ctrlAdmin, VntPrincipalI2 vntPrincipal) {
        initComponents();
        this.ctrlAdmin = ctrlAdmin;
        this.ctrlUsuario = ctrlUsuario;
        this.vntPrincipal = vntPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApellidp1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidp = new javax.swing.JTextField();
        cbxTipoTelf = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registrar");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imgs/register.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Correo");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Telefono");

        jLabel7.setText("Elija tipo de telefono");

        txtCedula.setText("0101010101");

        txtNombre.setText("1");

        txtApellidp.setText("1");

        cbxTipoTelf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*** Elija tipo ***", "Casa", "Movil" }));
        cbxTipoTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoTelfActionPerformed(evt);
            }
        });

        txtCorreo.setText("admin@gmail.com");

        txtContrasenia.setText("1");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnRegistrar)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxTipoTelf, 0, 154, Short.MAX_VALUE)
                                    .addComponent(txtContrasenia)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellidp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedula.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellidp.getText();
        int opcion = cbxTipoTelf.getSelectedIndex();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String contrasenia = txtContrasenia.getText();

        if (cedula.isBlank() || nombre.isBlank() || apellido.isBlank() || opcion == 0
                || telefono.isBlank() || correo.isBlank() || contrasenia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Existen campos en blanco");
        } else {
            System.out.println("---? " + ctrlAdmin.comprobarDatosAdmin(correo, cedula));
            System.out.println("---? " + ctrlUsuario.comprobarDatos(correo, cedula));
            if (ctrlAdmin.comprobarDatosAdmin(correo, cedula) && ctrlUsuario.comprobarDatos(correo, cedula)) {
                if (telefono(telefono) && cedula(cedula) && correoC(correo)) {
                    var admin = new AdminP(cedula, nombre, apellido, telefono, correo, contrasenia, 40, 0);
                    ctrlAdmin.create(admin);
                    System.out.println("---> " + admin);
                    JOptionPane.showMessageDialog(this, "Registrado Correctamente");
                    this.dispose();
                    vntPrincipal.getRegistrarAdminMenuvnttItem().setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Existen datos incorrectos");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hay datos que ya se han registrados anteriormente, \n Verifique ssus datos nuevamente");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        limpiar();
        txtCedula.setText("");
        txtTelefono.setEditable(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void cbxTipoTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoTelfActionPerformed
        // TODO add your handling code here:
        if (cbxTipoTelf.getSelectedIndex() == 1) {
            txtTelefono.setEditable(true);
            txtTelefono.setToolTipText("2424242");
        } else if (cbxTipoTelf.getSelectedIndex() == 2) {
            txtTelefono.setEditable(true);
            txtTelefono.setToolTipText("0984851714");
        }
    }//GEN-LAST:event_cbxTipoTelfActionPerformed

    public boolean telefono(String telefono) {
        if (cbxTipoTelf.getSelectedItem().equals("Casa")) {
            System.out.println("casa");
            Pattern tipo = Pattern.compile("^(4|2)?\\d{6,6}$");
            Matcher m = tipo.matcher(telefono);
            System.out.println("1 " + m.matches());
            return m.matches();
        } else if (cbxTipoTelf.getSelectedItem().equals("Movil")) {
            System.out.println("movil");
            Pattern tipo = Pattern.compile("^(09)?\\d{8,8}$");
            Matcher m = tipo.matcher(telefono);
            System.out.println("1 " + m.matches());
            return m.matches();
        }
        return false;
    }

    public boolean cedula(String numCedula) {
        Pattern p = Pattern.compile("^[0-2]\\d{9,9}$");
        Matcher m = p.matcher(numCedula);
        System.out.println("2 " + m.matches());
        return m.matches();
    }

    public boolean correoC(String correo) {
        Pattern texto = Pattern.compile("^\\S\\w{3,}@\\w{2,}(\\.\\w{2,})+$");
        Matcher corpus = texto.matcher(correo);
        System.out.println("3 " + corpus.matches());
        return corpus.matches();
    }

    public void limpiar() {
        txtNombre.setText("");
        txtApellidp.setText("");
        txtCorreo.setText("");
        txtContrasenia.setText("");
        cbxTipoTelf.getItemAt(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxTipoTelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellidp;
    private javax.swing.JTextField txtApellidp1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
